config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  root 'unis#top'

  resources :unis, only: :index do
      get 'choose', on: :collection
      resources :products, only: [:index, :show, :create, :destroy] do
         collection do
          post "add", to: "favorites#create"
          get 'search'
          get 'search_color'
          get 'search_price'
         end
         resources :bookings, only: [:new, :create]
           collection do
             get 'top'
             get 'kimono_list'
           end
      end
  end

  resources :students, only: [:show]
  resources :favorites, only: [:create, :destroy]
  resources :product_images, only: [:new, :create]

  get 'top' => 'unis#top'
  get 'uni/search' => 'unis#search'
  get 'catalog' => 'products#kimono_list'
  delete 'comments' => 'products#destroy'
  get 'photo' => 'products#form'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :eventdate
  belongs_to :product
  belongs_to :student
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :products
  has_many :dicounts
  has_many :eventdates
  has_many :eventdetails

before_save :geocode_full_address

  def geocode_full_address
    coords = Geocoder.coordinates(
      self.prefecture + self.city + self.address # 県名 + 市町村名 + 丁目番地
    )
    self.latitude = coords[0]
    self.longitude = coords[1]
  end
end

app/models/discount.rb
class Discount < ApplicationRecord
  belongs_to :company
  belongs_to :uni
end

app/models/eventdate.rb
class Eventdate < ApplicationRecord
  belongs_to :uni
  belongs_to :company
  has_many :bookings
end

app/models/eventdetail.rb
class Eventdetail < ApplicationRecord
  belongs_to :company
  belongs_to :uni
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :student
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :company
  has_many :bookings
  has_many :comments
  has_many :sample_images
  has_many :product_images
  has_many :students, through: :favorites
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
  mount_uploader :photo, ImageUploader
end

app/models/sample_image.rb
class SampleImage < ApplicationRecord
  belongs_to :product
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookings
  has_many :comments
  has_many :favorites
  has_many :products, through: :favorites
  belongs_to :uni
end

app/models/uni.rb
class Uni < ApplicationRecord
  has_many :discounts
  has_many :eventdates
  has_many :eventdetails
  has_many :students
  scope :incremental_search, -> (name){ where('name LIKE(?)',"%#{name}%") }
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

before_action :authenticate_student!, only: :new

  def new
    @booking = Booking.new
    @uni = Uni.find(params[:uni_id])
    @product = Product.find(params[:product_id])
    @student = current_student
    @eventdates = Eventdate.where(uni_id: params[:uni_id], company_id: @product.company.id)
  end

  def create
    Booking.create(create_params)
    @uni = Uni.find(params[:uni_id])
    @product = Product.find(params[:product_id])
    @student = current_student
    @eventdates = Eventdate.where(uni_id: params[:uni_id], company_id: @product.company.id)
    @booking = Booking.where(stuednt_id: current_student.id)
  end

  def create_params
    params.require(:booking).permit(:eventdate_id, :text).merge(product_id: params[:product_id], student_id: current_student.id)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_uni, only: [:index, :show,:search, :search_color, :search_price]

  def kimono_list
  end

  def show
    @product = Product.find(params[:id])
    @comments = Comment.where(product_id: @product.id)
    @comment = Comment.new
    @discount = Discount.where(university_id: @uni.id, company_id: @product.company.id)
    @eventdetail = Eventdetail.where(company_id: @product.company.id)
  end

  def create
    # binding.pry
    Comment.create(comment_params)
    @product = Product.find(params[:comment][:product_id])
    @comments = Comment.where(product_id: @product.id).last
  end

  def destroy
    Comment.find(params[:format]).destroy
    @product = Product.find(params[:comment][:product_id])
    @comments = Comment.where(product_id: @product.id).last
  end

 def index
    @products = Product.all
    @eventdetail = Eventdetail.all
 end

 def search
  @products = Product.new
  @products = Product.where('title LIKE(?)', "%#{params[:keyword]}%")
 end

 def search_color
  @products = Product.new
  @products = Product.where(color: params[:product])
end

  def search_price
  @products = Product.new
  @products = Product.where(range: params[:price])
  end

  def form
  # Product_image.create(product_params)
   @product_image = ProductImage.new
  # @product_image ||= nil
  end

  def form_create
    @product_image = ProductImage.find(params[:id])
    @product_image.save
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :image, :image_cache, :remove_image)
  end

  def comment_params
    params.require(:comment).permit(:text, :student_id, :product_id)
  end

  def set_uni
    @uni = Uni.find(params[:uni_id])
  end
end

app/controllers/unis_controller.rb
class UnisController < ApplicationController
 def top
 end

 def index
  @universities = Uni.all
 end

def search
  @unis = Uni.new
  @unis = Uni.where('name LIKE(?)', "%#{params[:keyword]}%")
end

def choose
  @unis = Uni.incremental_search(params[:name])
  respond_to do |format|
    format.json
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/product_images_helper.rb
module ProductImagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/unis_helper.rb
module UnisHelper
end

app/views/bookings/create.html.erb
<div class="bookingpage">
<div class="bookingbox">

<p>予約が完了しました！</p>
<a href="/students/<%= current_student.id %>" class="check_mypage">マイページで確認</a>

<div class="snsshare">↓友達に教える↓</div>
<%= social_share_button_tag("袴の試着なら", :url =>"https://infinite-ocean-88626.herokuapp.com/") %>
</div>
</div>

app/views/bookings/new.html.erb
<div class="bookingpage">
<div class="bookingbox">
<h1>試着を予約</h1>
<br>

<table>
 <tbody>
   <tr>
    <th scope="row" class>
     お名前
    </th>
    <td>
     <%= @student.name %>
    </td>
  </tr>
  <tr>
    <th scope="row" class>
     卒業する大学
    </th>
    <td>
     <%= @uni.name %>
    </td>
  </tr>
  <tr>
    <th scope="row" class>
     試着する商品
    </th>
    <td>
     <%= @product.title %>
    </td>
  </tr>
  <tr>
    <th scope="row" class>
     日時
    </th>
    <td>
     <%= form_for ([@uni, @product, @booking]) do |f| %>
     <%= f.collection_select :eventdate_id, @eventdates, :id, :time %>
    </td>
  </tr>
  <tr>
    <th scope="row" class>
     ご希望
    </th>
    <td>
     <%= f.text_area :text, :placeholder => "例: 他の色を合わせてみたい！"%>
    </td>
  </tr>
 </tbody>
 </table>

 <img class="bookingphoto" src="<%= @product.product_images[0].photo %>">
</div>
<div class="subbox">
   <%= f.submit "予約する", :class=> "booking_submit" %>
</div>

<% end %>




</div>

app/views/products/create.js.erb
$("#comment_list").append("<%= j(render @comments) %>");
$("#comment_text").val('');

app/views/products/destroy.js.erb
$("ol").html("<%= j(render @comments) %>")

app/views/products/index.html.erb
<div id="Contents">
<div class="product_index">
  <div class="inner">
  <section class="colSect" id="Collection">


      <a href="/top" class="breadcrumbs-link">Home</a>
              <span class="breadcrumbs-separator">/</span>
              <a href="/unis" class="breadcrumbs-link">大学検索</a>
              <span class="breadcrumbs-separator">>>></span>
              <a href="/unis/<%= @uni.id %>/products" class="breadcrumbs-link"><%= @uni.name %>で予約できる商品一覧</a>
            </div>

            <div class="uni-box">
            <div class="uni_name_line">
            <p><%= @uni.name %></p>で予約できる袴一覧
            </div>
            <div  class="uni-info">
            卒業式日程:  <%= @uni.graduation %>
            </div>
            </div>




      <div class="product_search_box">
            <li>
                <%= form_tag(search_uni_products_path(@uni.id), method: :get, class: "product_search_form") do %>
                      <input type="text" id="search" class="product_search_form" name="keyword" placeholder="キーワードで検索" required>
                      <input type="submit" value="検索" id="submit">
                <% end %>
            </li>
            <li>
            <%= form_tag(search_color_uni_products_path(@uni.id), method: :get, class: "product_search_form") do %>
            <%= select_tag 'product', options_for_select([["赤・エンジ",1],["紺・青",2],["ピンク",3],["白・クリーム",4],["黒・グレー",5],["緑",7],["黄・オレンジ",8],["紫",9]]), class: "product_search_form" %>
             <%= submit_tag("検索") %>
             <% end %>
             </li>
             <li>
             <%= form_tag(search_price_uni_products_path(@uni.id), method: :get, class: "product_search_form") do %>
            <%= select_tag 'price', options_for_select([["〜30,000円",1],["30,000〜40,000円",2],["40,000円〜50,000円",3],["50,000円〜60,000円",4],["60,000円〜70,000円",5],["70,000円〜",6]]), class: "product_search_form" %>
             <%= submit_tag("検索") %>
             <% end %>
             </li>

      </div>


           <ul class="product_list_wrapper">
           <% @products.each do |kimono| %>
              <li class="eachbox">
                <div class="kimonopic">
                  <% num = 1 %>
                  <% kimono.product_images.each do |pic| %>

                <a href="/unis/<%= @uni.id %>/products/<%= kimono.id %>">
                    <% if num == 1%>
                     <%= image_tag pic.photo %>

                    <% end %>
                    <% num += 1 %>
                  <% end %>
                  </a>
                </div>
                <div class="kimono_details">
                    <a href="/unis/<%= @uni.id %>/products/<%= kimono.id %>">
                     <p><%= kimono.price %>円</p>
                     <%= kimono.title %>


                    </a>
                </div>
              </li>

         <% end %>

           </ul>
  </section>
  </div>
  </div>
</div>

app/views/products/kimono_list.html.erb
<h1>袴一覧</h1>_
<p>image1 price1
image2 price2
image3 price3
...</p>

app/views/products/new.html.erb
<div class="field">
  <%= form_for(@product_image, url: "") do |f| %>
    <%= image_tag @product_image.photo.url if @product_image.present? %>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  <% end %>
</div>

app/views/products/search.html.erb
<div id="Contents">
<div class="product_index">
  <div class="inner">
  <section class="colSect" id="Collection">



   <a href="/top" class="breadcrumbs-link">Home</a>
              <span class="breadcrumbs-separator">/</span>
              <a href="/unis" class="breadcrumbs-link">大学検索</a>
              <span class="breadcrumbs-separator">/</span>
              <a href="/unis/<%= @uni.id %>/products" class="breadcrumbs-link"><%= @uni.name %>で予約できる商品一覧</a>
              <span class="breadcrumbs-separator">>>></span>検索結果
            </div>

            <div class="uni-box">
            <div class="uni_name_line">
            検索結果
            </div>
            </div>


<ul class="product_list_wrapper">
           <% @products.each do |kimono| %>
              <li class="eachbox">
                <div class="kimonopic">
                  <% num = 1 %>
                  <% kimono.product_images.each do |pic| %>

                <a href="/unis/<%= @uni.id %>/products/<%= kimono.id %>">
                    <% if num == 1%>
                     <%= image_tag pic.photo %>

                    <% end %>
                    <% num += 1 %>
                  <% end %>
                  </a>
                </div>
                <div class="kimono_details">
                    <a href="/unis/<%= @uni.id %>/products/<%= kimono.id %>">
                     <p><%= kimono.price %>円</p>
                     <%= kimono.title %>


                    </a>
                </div>
                <!-- <a href="/unis/<%= @uni.id %>/products/<%= kimono.id %>" class="kimonodetail">
                <p class="kimonodetail">
                  <span>詳細はこちら</span>
                </p>
                </a> -->
              </li>

              <% end %>

           </ul>





  </section>
  </div>
  </div>
</div>

app/views/products/search_color.html.erb
<div id="Contents">
<div class="product_index">
  <div class="inner">
  <section class="colSect" id="Collection">



   <a href="/top" class="breadcrumbs-link">Home</a>
              <span class="breadcrumbs-separator">/</span>
              <a href="/unis" class="breadcrumbs-link">大学検索</a>
              <span class="breadcrumbs-separator">/</span>
              <a href="/unis/<%= @uni.id %>/products" class="breadcrumbs-link"><%= @uni.name %>で予約できる商品一覧</a>
              <span class="breadcrumbs-separator">>>></span>検索結果
            </div>

            <div class="uni-box">
            <div class="uni_name_line">
            検索結果
            </div>
            </div>


<ul class="product_list_wrapper">
           <% @products.each do |kimono| %>
              <li class="eachbox">
                <div class="kimonopic">
                  <% num = 1 %>
                  <% kimono.product_images.each do |pic| %>

                <a href="/unis/<%= @uni.id %>/products/<%= kimono.id %>">
                    <% if num == 1%>
                     <%= image_tag pic.photo %>

                    <% end %>
                    <% num += 1 %>
                  <% end %>
                  </a>
                </div>
                <div class="kimono_details">
                    <a href="/unis/<%= @uni.id %>/products/<%= kimono.id %>">
                     <p><%= kimono.price %>円</p>
                     <%= kimono.title %>


                    </a>
                </div>
                <!-- <a href="/unis/<%= @uni.id %>/products/<%= kimono.id %>" class="kimonodetail">
                <p class="kimonodetail">
                  <span>詳細はこちら</span>
                </p>
                </a> -->
              </li>

              <% end %>

           </ul>



  </section>
  </div>
  </div>
</div>

app/views/products/search_price.html.erb
<div id="Contents">
<div class="product_index">
  <div class="inner">
  <section class="colSect" id="Collection">




   <a href="/top" class="breadcrumbs-link">Home</a>
              <span class="breadcrumbs-separator">/</span>
              <a href="/unis" class="breadcrumbs-link">大学検索</a>
              <span class="breadcrumbs-separator">/</span>
              <a href="/unis/<%= @uni.id %>/products" class="breadcrumbs-link"><%= @uni.name %>で予約できる商品一覧</a>
              <span class="breadcrumbs-separator">>>></span>検索結果
            </div>

            <div class="uni-box">
            <div class="uni_name_line">
            検索結果
            </div>
            </div>


<ul class="product_list_wrapper">
           <% @products.each do |kimono| %>
              <li class="eachbox">
                <div class="kimonopic">
                  <% num = 1 %>
                  <% kimono.product_images.each do |pic| %>

                <a href="/unis/<%= @uni.id %>/products/<%= kimono.id %>">
                    <% if num == 1%>
                     <%= image_tag pic.photo %>

                    <% end %>
                    <% num += 1 %>
                  <% end %>
                  </a>
                </div>
                <div class="kimono_details">
                    <a href="/unis/<%= @uni.id %>/products/<%= kimono.id %>">
                     <p><%= kimono.price %>円</p>
                     <%= kimono.title %>


                    </a>
                </div>
              </li>

              <% end %>

           </ul>



  </section>
  </div>
  </div>
</div>

app/views/products/select_options.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SelectKimono</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
</head>

<body>
<div class="uni_name_line">
<%= @uni.name %>で予約できる袴一覧
</div>

<div class="maincontents">
   <h1 class="listtitle">商品一覧</h1>
     <ul class="productlist">
     <% @products.each do |kimono| %>
        <li>
          <div class="kimonopic">
            <% num = 1 %>
            <% kimono.product_images.each do |pic| %>
          <a href="/products/<%= kimono.id %>?uni=<%= params[:id]%>" class="eachpic">
              <% if num == 1%>
                <img class="eachpic" src="<%= pic.image %>">
              <% end %>
              <% num += 1 %>
            <% end %>
            </a>
          </div>
          <a href="/products/<%= kimono.id %>?uni=<%= params[:id]%>" class="kimonodetail">
          <p class="kimonodetail">
            <span>詳細はこちら</span>
          </p>
          </a>
        </li>

        <% end %>

     </ul>
</div>


</body>
</html>

app/views/products/show.html.erb
  <div class="product_main_container">
    <div class="breadcrumbs-container">
        <a href="/top" class="breadcrumbs-link">Home</a>
        <span class="breadcrumbs-separator">/</span>
         <a href="/unis" class="breadcrumbs-link">大学検索</a>
        <span class="breadcrumbs-separator">/</span>
        <a href="/unis/<%= @uni.id %>/products" class="breadcrumbs-link"><%= @uni.name %>の商品一覧</a>
        <span class="breadcrumbs-separator">>>></span>
        <a href="/unis/<%= @uni.id %>/products/<%= @product.id %>" class="breadcrumbs-bold-link breadcrumbs-link">商品詳細</a>
    </div>

    <div class="production_details">
        <div class="pdp-image-container">
                <div class="thumbnails-vertical-container">

                   <% if @product.product_images[2].present? %>
                       <img class="thumbnails-thumbnail" src="<%= @product.product_images[2].photo %>">
                       <% end %>


                   <% if @product.product_images[1].present? %>
                       <img class="thumbnails-thumbnail" src="<%= @product.product_images[1].photo %>">
                       <% end %>

                </div>

                <div style="display: inline-block;">
                <% if @product.product_images[0].present? %>
                   <img class="thumbnails-selected-image" src="<%= @product.product_images[0].photo %>">
                   <% end %>
                </div>
        </div>

        <div class="pdp-description-container">
              <div class="pdp-price-info">
                   <h1 class="pdp-title"><%= @product.title %></h1>
                   <p class="pdp-selling-price"><a href="http://www.saganokan.com/" class="pdp-price" style="text-decoration: none;"><%= @product.company.name %></a></p>
                   <div class="product-size">袴サイズ   <%= @product.size %></div>

                   <p class="product-price priceinf"><%= @product.price %></p><div class="pricebox priceinf">円（税抜）</div>
            </div>



          <div class="eventdetail">
            この商品を試着するには...<br>
              <% @eventdetail.each do |detail| %>
                   <% if detail.present? %>
                    <p>① 大学の展示会場で試着</p>
                      <div class="detailbox">
                        <ul>
                          <li><%= simple_format(detail.period) %></li>
                          <li>時間：<%= detail.time %></li>
                          <li>会場：<%= detail.place %></li>
                        </ul>
                      </div>
                    <p>② 店舗で試着</p>
                      <div class="detailbox">
                        <%= @product.company.text %>
                  <% else %>
                    <p>店舗で試着</p>
                        <%= @product.company.text %>
                      </div>
                  <% end %>
               <% end %>
          </div>


            <div style='width: 100%;'>
                <div id="map" style='padding: 0 0 10px; margin: 10px 0px; margin-right: 0; width: 93%; height: 25vh;'></div>
            </div>

          <% @discount.each do |discount| %>
          <div class="discount"><p><%= @product.company.name %>でのご予約で</p><br><%= discount.text %></div>
          <% end %>

            <div class="pdp-action-container pdp-fixed">
                   <button class="pdp-add-to-wishlist pdp-button pdp-add-to-wishlist pdp-button">
                   <span><%= link_to "お気にいり", favorites_path(@product.id, uni_id: @uni.id), method: :post, class: "pdp-add-to-wishlist" %></span>
                   </button>

                   <a href="/unis/<%= @uni.id %>/products/<%= @product.id %>/bookings/new"><button class="pdp-add-to-bag pdp-button"><span>試着を予約</span></button>
                   </a>
            </div>
      </div>
      </div>
<div class="pdp_bottom">
      <div class="pdp-productDescriptors"><p>商品説明</p></div>
            <div class="set-include">
            <%= @product.set %></div>
            <div class="product_explain">
            <%= @product.text %>
            </div>
     <p class="comtitle">この商品に対するコメント</p>
       <%if student_signed_in? %>
            <%= form_for ([@uni, @comment]), remote: true, :url => {:action => 'create'} do |f| %>
              <%= f.hidden_field :student_id, value: current_student.id %>
              <%= f.hidden_field :product_id, value: @product.id %>
              <%= f.text_field :text %>
              <%= f.submit '投稿' %>
            <% end %>
       <% end %>

             <ol class="comment_box">


              <% @comments.each do |comment| %>
                <%= render partial: "comments/comment", locals: {comment: comment} %>
              <% end %>
              <div id="comment_list"></div>
            </ol>
</div>
    </div>
    </div>


<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers([
      {
        "lat": <%= @product.company.latitude %>,
        "lng": <%= @product.company.longitude %>,
        "picture": {
          "width":  32,
          "height": 32
        },
        "infowindow": '<%= @product.company.name %>'
      }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(15);
  });
</script>

app/views/unis/index.html.erb
<div class="uni_index">

    <div class="unilistbody">
         <div class="unilist_title">卒業する大学を選択</div>
        <% @universities.each do |uni| %>
        <div class="unilist">
            <a href="/unis/<%= uni.id %>/products" class="uniname"><%= uni.name %></a>
        </div>
          <p class="unilist_date">卒業式：<%= uni.graduation %></p>
        <% end %>
    </div>

</div>

app/views/unis/search.html.erb
<div class="uni_index">

    <div class="unilistbody">
         <div class="unilist_title">検索結果（卒業する大学を選択）</div>
        <% @unis.each do |uni| %>
        <div class="unilist">
            <a href="/unis/<%= uni.id %>/products" class="uniname"><%= uni.name %></a>
        </div>
          <p class="unilist_date">卒業式：<%= uni.graduation %></p>
        <% end %>
    </div>

</div>

app/views/unis/top.html.erb
<div class="main_container">
<div class="introduction">


  <%= image_tag "/assets/topimage.jpg" %>
     <div class="intro_box">
              <div class="overlay">
                 <h1>
                    find and book your best memory...
                   <br>
                  <p>卒業生のためのレンタル袴比較＆試着の予約サイト</p>
                  </h1>
                  <div class="button-wrap3">
                    <a href="/unis" class="button3">
                      袴をさがす
                     </a>
                  </div>
              </div>
    </div>


</div>

 <div class="row">
 <%= image_tag "/assets/hakamaps1.png", :class=>"triangle1" %>
 <%= image_tag "/assets/iphone1.png", :class=>"triangle2" %>
        <div class="featured-title">
          <h3 class="whatwedo" style="padding-top: 0px; opacity: 1;">WHAT WE DO</h3>
          <h4 class="explanation1">自分の卒業する大学の展示イベントや、お得なキャンペーン情報を<br>まとめて検索、試着の予約までできる！</h4>
          <h4 class="explanation2">お店のカタログ写真に加え、<br>過去の卒業生のコーディネートまで含めた膨大なデザインから選べる！</h4>
           <div class="button-wrap2">
                    <a href="/unis" class="button2">
                      袴をさがす
                     </a>
                  </div>
        </div>
      </div>




</div>