config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  root 'unis#top'

  resources :unis, only: :index do
      get 'choose', on: :collection
      resources :products, only: [:index, :show, :create, :destroy] do
         collection do
          post "add", to: "favorites#create"
          get 'search'
          get 'search_color'
          get 'search_price'
         end
         resources :bookings, only: [:new, :create]
           collection do
             get 'top'
             get 'kimono_list'
           end
      end
  end

  resources :students, only: [:show]
  resources :favorites, only: [:create, :destroy]
  resources :product_images, only: [:new, :create]

  get 'top' => 'unis#top'
  get 'uni/search' => 'unis#search'
  get 'catalog' => 'products#kimono_list'
  delete 'comments' => 'products#destroy'
  get 'photo' => 'products#form'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :eventdate
  belongs_to :product
  belongs_to :student
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :products
  has_many :dicounts
  has_many :eventdates
  has_many :eventdetails

before_save :geocode_full_address

  def geocode_full_address
    coords = Geocoder.coordinates(
      self.prefecture + self.city + self.address # 県名 + 市町村名 + 丁目番地
    )
    self.latitude = coords[0]
    self.longitude = coords[1]
  end
end

app/models/discount.rb
class Discount < ApplicationRecord
  belongs_to :company
  belongs_to :uni
end

app/models/eventdate.rb
class Eventdate < ApplicationRecord
  belongs_to :uni
  belongs_to :company
  has_many :bookings
end

app/models/eventdetail.rb
class Eventdetail < ApplicationRecord
  belongs_to :company
  belongs_to :uni
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :student
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :company
  has_many :bookings
  has_many :comments
  has_many :sample_images
  has_many :product_images
  has_many :students, through: :favorites
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
  mount_uploader :photo, ImageUploader
end

app/models/sample_image.rb
class SampleImage < ApplicationRecord
  belongs_to :product
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookings
  has_many :comments
  has_many :favorites
  has_many :products, through: :favorites
  belongs_to :uni
end

app/models/uni.rb
class Uni < ApplicationRecord
  has_many :discounts
  has_many :eventdates
  has_many :eventdetails
  has_many :students
  scope :incremental_search, -> (name){ where('name LIKE(?)',"%#{name}%") }
end

app/controllers/unis_controller.rb
class UnisController < ApplicationController
 def top
 end

 def index
  @universities = Uni.all
 end

def search
  @unis = Uni.new
  @unis = Uni.where('name LIKE(?)', "%#{params[:keyword]}%")
end

def choose
  @unis = Uni.incremental_search(params[:name])
  respond_to do |format|
    format.json
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/products_helper.rb
module ProductsHelper

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/unis_helper.rb
module UnisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oriapp</title>
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//maps.google.com/maps/api/js?key=AIzaSyBPow4J6sM5xM-ExrVj_tQ70yQ0SiYjwkc"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>


<header>
    <div class = "title-box">

          <%= form_tag('/uni/search', method: :get, class: "form-wrapper-top") do %>
                     <input type="text" id="search" name="keyword" placeholder="大学名を入力" required>
                    <input type="submit" value="検索" id="submit">
          <% end %>
    </div>

<div class="original_menu">
   <span class="cls"></span>
   <span>
      <nav class="main-nav" role="navigation">
        <ul id="menu" class="submenu">
        <li><a href="/top" title="home">HOME</a>
        </li>
        <li><a href="#" title="about">ABOUT</a>
        </li>
        <li><a href="/unis" title="unilist">大学一覧</a>
        </li>
        <li><a href="" title="account">アカウント</a>
          <ul>
            <li><a href="/students/sign_up" title="new">新規登録</a></li>
            <li><%if student_signed_in? %>
                   <%= link_to  "ログアウト",destroy_student_session_path, method: :delete, class: "a" %>
                <% else %>
                  <a href="/students/sign_in" title="login">ログイン</a>
                <% end %>
            </li>
            <%if student_signed_in? %>
                   <li><a href="/students/<%= current_student.id %>" title="mypage">マイページ</a>
                <% end %>  </li>
          </ul>
        </li>
        <li><a href="#" title="contact">お問い合わせ</a>
        </li>

      </ul>
    </nav>
    </span>
    <span class="cls"></span>
  </div>

</header>

<body>

    <div class = iphone_header>
    <a href="/top" class="webtitle">Hakama-Book</a>
          <%= form_tag('/unis/search', method: :get, class: "form-wrapper-top") do %>
                     <input type="text" id="search" name="keyword" placeholder="大学名を入力" required>
                    <input type="submit" value="検索" id="submit">
          <% end %>
    </div>

<div class="open">
   <span class="cls"></span>
   <span>
      <nav class="main-nav" role="navigation">
        <ul id="menu" class="submenu">
        <li><a href="/top" title="home">HOME</a>
        </li>
        <li><a href="/unis" title="unilist">大学一覧</a>
        </li>
        <li><a href="/students/sign_up" title="new">新規登録</a></li>
        <li><%if student_signed_in? %>
                   <%= link_to  "ログアウト",destroy_student_session_path, method: :delete, class: "a" %>
                <% else %>
                  <a href="/students/sign_in" title="login">ログイン</a>
                <% end %>
            </li>
            <%if student_signed_in? %>
        <li><a href="/students/<%= current_student.id %>" title="mypage">マイページ</a> <% end %>  </li>
        </li>

      </ul>
    </nav>
    </span>
    <span class="cls"></span>
  </div>

<%= yield %>
</body>

<footer>
 <div class="sns-share">
 <%= social_share_button_tag("袴の試着なら", :url =>"https://infinite-ocean-88626.herokuapp.com/") %>
 </div>
</footer>
</html>